Adding sample code
DulLabs/bhai-lang pull request #151
Opened 2022-03-14 20:41 UTC by rishikav

Adding sample bhai-lang code for fibonacci series.

2022-03-15 01:23 UTC, abhi1510abhi approved these changes

2022-03-15 03:04 UTC, impratik7 approved these changes
Sounds too good 😄 👍

2022-03-15 17:07 UTC, aniketsingh0104 requested changes
Nit : Fix indentation.

2022-03-18 15:21 UTC, ritikbanger commented on sample/Fibonacci.bhai
> +bye bhai
Update your file with this code. Though BhaiLang can work without indentation, but as suggested, you can use it.

```
hi bhai

  bol bhai "Fibonacci likhenge";
  bhai ye hai start = 0;
  bhai ye hai next = 1;
  bol bhai start;
  bol bhai next;
  bhai ye hai n = 0;
  jab tak bhai (n < 10) {
    bhai ye hai nextKaNext = start + next;
    bol bhai nextKaNext;
    start = next;
    next = nextKaNext;
    n += 1;
  }

bye bhai
```

2022-03-18 18:51 UTC, rishikav commented
I have made the requested changes but I am unable to understand the error. Could you please help out?

2022-03-19 18:46 UTC, aniketsingh0104 commented
Hey. Thanks for this but as of now we won't be adding this in this repo. If you wish you can create a separate repo for these sample codes like this - https://github.com/carrotfarmer/bhai-lang .

2022-03-19 18:46 UTC, closed without merging